const NoteActionTypes = {
	FETCH_USER_VIDEO_NOTES_START: "FETCH_USER_NOTES_START",
	FETCH_USER_VIDEO_NOTES_SUCCESS: "FETCH_USER_NOTES_SUCCESS",
	FETCH_USER_VIDEO_NOTES_FAILURE: "FETCH_USER_NOTES_FAILURE",

	ADD_VIDEO_NOTE_START: "ADD_VIDEO_NOTE_START",
	ADD_VIDEO_NOTE_SUCCESS: "ADD_VIDEO_NOTE_SUCCESS",
	ADD_VIDEO_NOTE_FAILURE: "ADD_VIDEO_NOTE_FAILURE",

	TOGGLE_NOTES_EDITABLE: "TOGGLE_NOTES_EDITABLE",

	DELETE_NOTE_START: "DELETE_NOTE_START",
	DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
	DELETE_NOTE_FAILURE: "DELETE_NOTE_FAILURE",

	UPDATE_NOTE_START: "UPDATE_NOTE_START",
	UPDATE_NOTE_SUCCESS: "UPDATE_NOTE_SUCCESS",
	UPDATE_NOTE_FAILURE: "UPDATE_NOTE_FAILURE",

	TOGGLE_EDIT_BOX_HIDDEN: "TOGGLE_EDIT_BOX_HIDDEN",
};

export default NoteActionTypes;
