const TopicActionTypes = {
	FETCH_TOPICS_START: 'FETCH_TOPICS_START',
	FETCH_TOPICS_SUCCESS: 'FETCH_TOPICS_SUCCESS',
	FETCH_TOPICS_FAILURE: 'FETCH_TOPICS_FAILURE',

	FETCH_TOPIC_VIDEOS_START: 'FETCH_TOPIC_VIDEOS_START',
	FETCH_TOPIC_VIDEOS_SUCCESS: 'FETCH_TOPIC_VIDEOS_SUCCESS',
	FETCH_TOPIC_VIDEOS_FAILURE: 'FETCH_TOPIC_VIDEOS_FAILURE',

	SET_CURRENT_TOPIC_ID: 'SET_CURRENT_TOPIC_ID',

	RESET_TOPIC_AND_VIDEOS: 'RESET_TOPIC_AND_VIDEOS',
};

export default TopicActionTypes;
